spring:
  profiles:
    active: prod

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true

---
spring:
  config:
    activate:
      on-profile: dev

  mail: # prod - cloud config
    username: ${GOOGLE_SMTP_ACCOUNT}
    password: ${GOOGLE_SMTP_PW}
